### ISSUE TITLE
'Duplicate row.names are not allowed'

### ISSUE THREAD

**Issue by jackcht** [jiang-hang/rstatscn#2] opened 2016-06-10 19:45 UTC
Hi, 
I tried your api on 'A1307' and 'A1308' recently and it returns this error. The JSONs returned by A1307 and A1308 have the duplicate 'name' and thus cannot be handled by data frame. Please check that, thanks. 

(same for both chinese and english)
(E.g. The data source have two series of date called '合资固定资产投资额_累计值' ('Investment in Fixed Assets, Joint-venture Enterprises, _Accumulated' as in English))

> -> `statscnQueryData('A1308',dbcode='hgyd')`
> 
>  **Error in row.names<-.data.frame(_tmp_, value = value) :** 
>   **duplicate 'row.names' are not allowed** 
> 
> 6 stop("duplicate 'row.names' are not allowed") 
> 5 row.names<-.data.frame(_tmp_, value = value) 
> 4 row.names<-(_tmp_, value = value) 
> 3 rownames<-(_tmp_, value = c("Investment in Fixed Assets, Accumulated(100 million yuan)", 
> "Investment in Fixed Assets, Accumulated Growth Rate(%)", "Investment in Fixed Assets, Domestic Funded, _Accumulated(100 million yuan)", 
> "Investment in Fixed Assets, Domestic Funded, _Accumulated Growth Rate(%)", 
> "Investment in Fixed Assets, State-owned Enterprises, _Accumulated(100 million yuan)",  ... at rstatscn_en.R#112
> 2 dataJson2df(ret, curQuery$rowcode, curQuery$colcode) at rstatscn_en.R#201
> 1 statscnQueryData("A1308", dbcode = "hgyd")

**Comment by jiang-hang** [comment] 2016-06-11 03:33
looks like it is a bug in the website. I'd like to figure out a way to let them know it.  Hopefully they can get it fixed.

**Comment by jiang-hang** [comment] 2016-07-20 05:09
the issue is fixed in 1.1.1 . call the statscnRowNamePrefix() before the query.

**Closed as completed by jiang-hang** 2016-07-20 05:09 UTC
